### ISSUE TITLE
Training fail

### ISSUE THREAD

**Issue by thuc248997** [nftblackmagic/Diffusion-Tryon-Trainer#12]
Dea project owner,
I had a bug when training.

`ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [512] and output size of (64, 64). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.`

Note: I tested code with val dataset, which is same train dataset

**Comment by nftblackmagic** [comment]
https://github.com/nftblackmagic/Diffusion-Tryon-Trainer/blob/6144c0061bdf1c7a2748d4d90d707e563a50a31e/ootd/pipelines_ootd/pipeline_ootd.py#L301C1-L302C43

Can you re-try to uncomment two lines?

**Comment by thuc248997** [comment]
@nftblackmagic many thanks. It is worked!
