### ISSUE TITLE
How to use your trained weights?

### ISSUE THREAD

**Issue by chg0901** [nftblackmagic/Diffusion-Tryon-Trainer#8]
Thanks for your great work. I have a question to ask as follows.

I download the weights you uploaded to the [huggingface](https://huggingface.co/xiaozaa/Diffusion-Tryon-Trainer), 

and it is in this format

```bash
.
├── unet_garm
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
└── unet_vton
    ├── config.json
    └── diffusion_pytorch_model.safetensors 

```

while in the `Diffusion-Tryon-Trainer/run/run_ootd_cp_dataset.py`, it shows that the `model_root` in this format like `/workspace/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000` 

How to use the `unet_garm` and `unet_garm`, and what's the differences between them?

**Comment by nftblackmagic** [comment]
Please use the inference_test_dataset.sh to run inference. `/workspace/OOTDiffusion/checkpoints/ootd/ootd_hd/checkpoint-36000` is the default value for official downloaded weights from huggingface. 
You can directly put ```.
├── unet_garm
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
└── unet_vton
    ├── config.json
    └── diffusion_pytorch_model.safetensors ```
    
    Under checkpoints dir. Or you can put the weight you want and change the arg --unet_root="./checkpoints/" \ in shell file.
    
    
You can check the official paper https://github.com/levihsu/OOTDiffusion to find more details about the differences betweent unet_garm and unet_vton. In short, one unet_garm is using conditioning to control the unet_vton denoise process.

**Comment by chg0901** [comment]
Thank you and I have managed it. 

I have one more question, why do you take a 512*512 resolution to train your model?

**Comment by nftblackmagic** [comment]
It's directly from DCI-VTON repo. I just directly use it without change. No special reasons.

**Comment by chg0901** [comment]
Got it. Thanks
